import { useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { Button, Field, Screen } from '@dineflow/shared';
import { useAuth } from '../stores/auth.store';
import { supabase } from '../lib/supabase';
export function Login(){const router=useRouter();const signIn=useAuth(s=>s.signIn);const profile=useAuth(s=>s.profile);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);return <Screen title="Operations sign in" subtitle="For restaurant staff and owners."><Field label="Email" keyboardType="email-address" autoCapitalize="none" value={email} onChangeText={setEmail}/><Field label="Password" secureTextEntry value={password} onChangeText={setPassword}/><Button title="Log in" busy={busy} onPress={async()=>{setBusy(true);try{await signIn(email,password);const role=useAuth.getState().profile?.role;if(role==='OWNER')router.replace('/(owner)/dashboard');else if(role==='STAFF')router.replace('/(staff)/dashboard');else{await useAuth.getState().signOut();Alert.alert('Access denied','This app requires a staff or owner account.');}}catch(e){Alert.alert('Sign in failed',String((e as Error).message));}finally{setBusy(false);}}}/><Button title="Forgot password?" kind="ghost" onPress={()=>router.push('/forgot-password')}/></Screen>}
export function ForgotPassword(){const [email,setEmail]=useState('');const router=useRouter();return <Screen title="Reset password" subtitle="We will email a reset link for your staff account."><Field label="Email" keyboardType="email-address" autoCapitalize="none" value={email} onChangeText={setEmail}/><Button title="Send reset link" onPress={async()=>{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'dineflow-operations://reset-password'});if(error)Alert.alert('Could not send link',error.message);else{Alert.alert('Check your email');router.push('/reset-password');}}}/></Screen>}
export function ResetPassword(){const [password,setPassword]=useState('');const router=useRouter();return <Screen title="Set new password"><Field label="New password" secureTextEntry value={password} onChangeText={setPassword}/><Button title="Save password" onPress={async()=>{const {error}=await supabase.auth.updateUser({password});if(error)Alert.alert('Could not reset password',error.message);else router.replace('/login');}}/></Screen>}
