import { useState } from 'react';
import { Alert } from 'react-native';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Field, Freshness, Heading, Label, Screen, State, StatusBadge, type Table, type QueueEntry, type Reservation } from '@dineflow/shared';
import { api } from '../lib/api';
import { Nav, useRealtime, useRestaurant } from './common';
import { useAuth } from '../stores/auth.store';
import { useLocalSearchParams, useRouter } from 'expo-router';
type Summary={bookings:number;waiting:number;tables:Record<string,number>;cancellations:number;no_shows:number;average_wait_minutes:number};
const colomboDay=(offset=0)=>new Date(Date.now()+330*60000+offset*24*60*60*1000).toISOString().slice(0,10);
const reservationActions:Record<string,string[]>={PENDING:['CONFIRMED','CANCELLED','NO_SHOW'],CONFIRMED:['ARRIVED','CANCELLED','NO_SHOW'],ARRIVED:['SEATED','CANCELLED','NO_SHOW'],SEATED:['COMPLETED']};
const tableActions:Record<string,string[]>={AVAILABLE:['RESERVED','OCCUPIED','UNAVAILABLE'],RESERVED:['AVAILABLE','OCCUPIED'],OCCUPIED:['CLEANING'],CLEANING:['AVAILABLE'],UNAVAILABLE:['AVAILABLE']};
export function Dashboard(){const id=useRestaurant();const role=useAuth(s=>s.profile?.role);const day=colomboDay();useRealtime('tables');useRealtime('queue_entries');useRealtime('reservations');const tables=useQuery({queryKey:['tables',id],enabled:!!id,queryFn:()=>api<Table[]>(`/tables?restaurant_id=${id}`)});const queue=useQuery({queryKey:['queue',id],enabled:!!id,queryFn:()=>api<QueueEntry[]>(`/queue?restaurant_id=${id}`)});const reservations=useQuery({queryKey:['reservations',id,day],enabled:!!id,queryFn:()=>api<Reservation[]>(`/reservations?restaurant_id=${id}&date=${day}`)});return <Screen title={role==='OWNER'?'Owner overview':'Service dashboard'} subtitle="Today's bookings, waiting parties, and tables in one place.">{!id?<State empty="Your account is not assigned to a restaurant."/>:<><Card><Heading>{reservations.data?.filter(r=>['PENDING','CONFIRMED','ARRIVED'].includes(r.status)).length??0} active bookings</Heading><Label>{queue.data?.filter(q=>['WAITING','NOTIFIED','TABLE_READY'].includes(q.status)).length??0} waiting parties</Label><Label>{tables.data?.filter(t=>t.status==='AVAILABLE').length??0} free tables</Label><Freshness at={new Date().toISOString()}/></Card>{tables.error||queue.error||reservations.error?<State error="Could not load the latest operations data." onRetry={()=>{void tables.refetch();void queue.refetch();void reservations.refetch()}}/>:null}</>}<Nav/></Screen>}
export function Tables(){const id=useRestaurant();const router=useRouter();const role=useAuth(s=>s.profile?.role);useRealtime('tables');const q=useQuery({queryKey:['tables',id],enabled:!!id,queryFn:()=>api<Table[]>(`/tables?restaurant_id=${id}`)});return <Screen title="Table status" subtitle="See available, occupied, reserved, and cleaning tables.">{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:q.data?.map(t=><Card key={t.id}><Heading>{t.label} · {t.capacity} seats</Heading><StatusBadge status={t.status}/><Freshness at={t.updated_at}/><Button title="View table" kind="secondary" onPress={()=>router.push(`/${role==='OWNER'?'(owner)':'(staff)'}/tables/${t.id}` as never)}/></Card>)}<Nav/></Screen>}
export function TableDetail(){const {tableId}=useLocalSearchParams<{tableId:string}>();const id=useRestaurant();useRealtime('tables');const client=useQueryClient();const q=useQuery({queryKey:['tables',id],enabled:!!id,queryFn:()=>api<Table[]>(`/tables?restaurant_id=${id}`)});const t=q.data?.find(x=>x.id===tableId);return <Screen title={t?.label??'Table details'} subtitle="Keep this table's state current for the whole team.">{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:t?<Card><Heading>{t.capacity} seats</Heading><StatusBadge status={t.status}/><Freshness at={t.updated_at}/>{(tableActions[t.status]??[]).map(status=><Button key={status} title={`Set ${status.toLowerCase()}`} kind="secondary" onPress={async()=>{try{await api(`/tables/${t.id}`,{method:'PATCH',body:{status}});await client.invalidateQueries({queryKey:['tables',id]});}catch(e){Alert.alert('Could not update table',String((e as Error).message));}}}/>)}</Card>:<State empty="Table not found."/>}<Nav/></Screen>}
export function Reservations(){const id=useRestaurant();useRealtime('reservations');const client=useQueryClient();const [search,setSearch]=useState('');const [day,setDay]=useState(colomboDay());const q=useQuery({queryKey:['reservations',id,day],enabled:!!id,queryFn:()=>api<(Reservation&{profiles?:{full_name:string;phone:string|null};tables?:{label:string}})[]>(`/reservations?restaurant_id=${id}&date=${day}`)});const list=q.data?.filter(r=>`${r.profiles?.full_name??''} ${r.tables?.label??''} ${r.starts_at}`.toLowerCase().includes(search.toLowerCase()));return <Screen title="Reservations" subtitle="Find guests and update arrival or seating."><Button title="Today" kind={day===colomboDay()?'primary':'secondary'} onPress={()=>setDay(colomboDay())}/><Button title="Tomorrow" kind={day===colomboDay(1)?'primary':'secondary'} onPress={()=>setDay(colomboDay(1))}/><Field label="Search reservations" value={search} onChangeText={setSearch}/>{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:list?.length?list.map(r=><Card key={r.id}><Heading>{r.profiles?.full_name||'Guest'}</Heading><Label>{new Date(r.starts_at).toLocaleString()} · {r.party_size} guests · {r.tables?.label??'Table pending'}</Label><Label muted>{r.profiles?.phone}</Label><StatusBadge status={r.status}/>{(reservationActions[r.status]??[]).map(status=><Button key={status} title={`Mark ${status.toLowerCase()}`} kind="secondary" onPress={()=>Alert.alert('Update reservation?',`Set status to ${status}?`,[{text:'Back'},{text:'Update',onPress:async()=>{try{await api(`/reservations/${r.id}`,{method:'PATCH',body:{status}});await client.invalidateQueries({queryKey:['reservations',id]});}catch(e){Alert.alert('Update failed',String((e as Error).message));}}}])}/>)}</Card>):<State empty="No matching reservations."/>}<Nav/></Screen>}
export function Queue(){const id=useRestaurant();useRealtime('queue_entries');const client=useQueryClient();const tables=useQuery({queryKey:['tables',id],enabled:!!id,queryFn:()=>api<Table[]>(`/tables?restaurant_id=${id}`)});const q=useQuery({queryKey:['queue',id],enabled:!!id,queryFn:()=>api<QueueEntry[]>(`/queue?restaurant_id=${id}`)});return <Screen title="Virtual queue" subtitle="Notify the next party, then seat them at an available table.">{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:q.data?.filter(e=>['WAITING','NOTIFIED','TABLE_READY'].includes(e.status)).length?q.data.filter(e=>['WAITING','NOTIFIED','TABLE_READY'].includes(e.status)).map(e=><QueueCard key={e.id} entry={e} tables={tables.data??[]} reload={()=>void client.invalidateQueries()}/>):<State empty="No parties waiting."/>}<Nav/></Screen>}
function QueueCard({entry:e,tables,reload}:{entry:QueueEntry;tables:Table[];reload:()=>void}){const [wait,setWait]=useState(String(e.estimated_wait_minutes));return <Card><Heading>#{e.position??'—'} · {e.customer_name}</Heading><Label>{e.party_size} guests · {e.phone??'No phone'}</Label><StatusBadge status={e.status}/><Field label="Estimated wait (minutes)" keyboardType="number-pad" value={wait} onChangeText={setWait}/><Button title="Update wait" kind="secondary" onPress={async()=>{try{await api(`/queue/${e.id}`,{method:'PATCH',body:{status:e.status,estimated_wait_minutes:Number(wait)}});reload()}catch(err){Alert.alert('Update failed',String((err as Error).message))}}}/><Button title="Notify table ready" disabled={e.status==='TABLE_READY'} onPress={async()=>{try{await api(`/queue/${e.id}`,{method:'PATCH',body:{status:'TABLE_READY'}});reload()}catch(err){Alert.alert('Notify failed',String((err as Error).message))}}}/>{tables.filter(t=>t.status==='AVAILABLE'&&t.capacity>=e.party_size).map(t=><Button key={t.id} title={`Seat at ${t.label}`} kind="secondary" onPress={async()=>{try{await api(`/queue/${e.id}/seat`,{method:'POST',body:{table_id:t.id}});reload()}catch(err){Alert.alert('Could not seat party',String((err as Error).message))}}}/>)}<Button title="Mark no-show" kind="danger" onPress={()=>Alert.alert('Mark no-show?',e.customer_name,[{text:'Back'},{text:'Confirm',onPress:async()=>{await api(`/queue/${e.id}`,{method:'PATCH',body:{status:'NO_SHOW'}});reload()}}])}/></Card>}
export function WalkIns(){const id=useRestaurant();const router=useRouter();const [name,setName]=useState('');const [phone,setPhone]=useState('');const [party,setParty]=useState('2');const [wait,setWait]=useState('15');const [busy,setBusy]=useState(false);return <Screen title="Add walk-in" subtitle="Add the party to the ordered virtual queue."><Field label="Customer name" value={name} onChangeText={setName}/><Field label="Phone (optional)" value={phone} keyboardType="phone-pad" onChangeText={setPhone}/><Field label="Party size" value={party} keyboardType="number-pad" onChangeText={setParty}/><Field label="Estimated wait in minutes" value={wait} keyboardType="number-pad" onChangeText={setWait}/><Button title="Add to queue" busy={busy} disabled={!name||!Number(party)||!id} onPress={async()=>{setBusy(true);try{await api('/queue',{method:'POST',body:{restaurant_id:id,customer_name:name,phone,party_size:Number(party),estimated_wait_minutes:Number(wait)}});router.replace('/(staff)/queue');}catch(e){Alert.alert('Could not add walk-in',String((e as Error).message))}finally{setBusy(false)}}}/><Nav/></Screen>}
export function Profile(){const router=useRouter();const auth=useAuth();return <Screen title="Your staff account"><Card><Heading>{auth.profile?.full_name}</Heading><Label>{auth.profile?.role}</Label></Card><Button title="Sign out" kind="secondary" onPress={async()=>{await auth.signOut();router.replace('/login')}}/><Nav/></Screen>}
export function Analytics(){const id=useRestaurant();const q=useQuery({queryKey:['analytics',id],enabled:!!id,queryFn:()=>api<Summary>(`/analytics/${id}`)});return <Screen title="Daily summary" subtitle="Today's operational picture.">{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:q.data?<Card><Heading>{q.data.bookings} bookings</Heading><Label>{q.data.waiting} waiting · {q.data.average_wait_minutes} min average wait</Label><Label>{q.data.cancellations} cancellations · {q.data.no_shows} no-shows</Label>{Object.entries(q.data.tables).map(([status,count])=><Label key={status}>{status}: {count}</Label>)}</Card>:null}<Nav/></Screen>}
