import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { OwnerLayout } from '../../../components/common/OwnerLayout';
import { ActionButton } from '../../../components/common/ActionButton';
import { COLORS, RADIUS } from '../../../constants/theme';

export default function RestaurantSettings() { const router=useRouter(); const [name,setName]=useState('DineFlow Restaurant'); const [phone,setPhone]=useState('+94 71 234 5678'); const [autoConfirm,setAutoConfirm]=useState(true); return <OwnerLayout active="more" title="Settings"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><View style={styles.hero}><Text style={styles.kicker}>RESTAURANT</Text><Text style={styles.title}>Restaurant settings</Text><Text style={styles.sub}>Keep your restaurant profile and operating preferences in one place.</Text></View><SectionTitle title="Restaurant details"/><View style={styles.card}><Text style={styles.label}>Restaurant name</Text><TextInput value={name} onChangeText={setName} style={styles.input}/><Text style={styles.label}>Contact number</Text><TextInput value={phone} onChangeText={setPhone} style={styles.input} keyboardType="phone-pad"/><ActionButton title="Save restaurant details" onPress={()=>Alert.alert('Saved','Restaurant details updated.')}/></View><SectionTitle title="Operations"/><View style={styles.card}><Setting title="Opening hours" subtitle="Set lunch and dinner service times" icon="time-outline" onPress={()=>router.push('/(owner)/settings/opening-hours')}/><Setting title="Booking & availability" subtitle="Control bookable times and reservation capacity" icon="calendar-outline" onPress={()=>router.push('/(owner)/settings/booking-settings')}/><Setting title="Table capacity" subtitle="Configure your service capacity" icon="grid-outline" onPress={()=>router.push('/(owner)/settings/capacity')}/><Setting title="Notifications" subtitle="Control operational alerts" icon="notifications-outline" onPress={()=>Alert.alert('Notifications','Notification preferences will be connected later.')}/></View><SectionTitle title="Booking preference"/><View style={styles.card}><View style={styles.switchRow}><View style={styles.switchIcon}><Ionicons name="flash-outline" size={17} color={COLORS.text}/></View><View style={{flex:1}}><Text style={styles.switchTitle}>Auto-confirm reservations</Text><Text style={styles.switchSub}>Confirm compatible requests automatically.</Text></View><Switch value={autoConfirm} onValueChange={setAutoConfirm} trackColor={{false:'#D9D9D5',true:COLORS.primary}} thumbColor={COLORS.white}/></View></View></ScrollView></OwnerLayout>; }
function SectionTitle({title}:{title:string}){return <Text style={styles.section}>{title}</Text>}; function Setting({title,subtitle,icon,onPress}:{title:string;subtitle:string;icon:keyof typeof Ionicons.glyphMap;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.setting}><View style={styles.settingIcon}><Ionicons name={icon} size={17} color={COLORS.text}/></View><View style={{flex:1}}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingSub}>{subtitle}</Text></View><Ionicons name="chevron-forward" size={17} color="#92928D"/></Pressable>}
const styles=StyleSheet.create({scroll:{paddingTop:5,paddingBottom:24},hero:{marginBottom:14},kicker:{fontSize:8.5,fontWeight:'900',color:COLORS.muted,letterSpacing:1.1,marginBottom:3},title:{fontSize:24,fontWeight:'900',color:COLORS.text},sub:{fontSize:10.5,lineHeight:15,color:COLORS.textSoft,marginTop:3},section:{fontSize:16,fontWeight:'900',color:COLORS.text,marginTop:3,marginBottom:9},card:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,borderWidth:1,borderColor:'#ECECE8',padding:13,marginBottom:12},label:{fontSize:10.5,fontWeight:'800',color:COLORS.text,marginBottom:6},input:{minHeight:44,borderWidth:1,borderColor:'#DADAD6',borderRadius:11,paddingHorizontal:12,fontSize:12,color:COLORS.text,backgroundColor:'#FAFAF8',marginBottom:11},setting:{minHeight:64,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#ECECE8'},settingIcon:{width:34,height:34,borderRadius:11,backgroundColor:COLORS.primarySoft,alignItems:'center',justifyContent:'center',marginRight:10},settingTitle:{fontSize:11.5,fontWeight:'900',color:COLORS.text},settingSub:{fontSize:9.2,color:COLORS.muted,lineHeight:14,marginTop:2},switchRow:{flexDirection:'row',alignItems:'center'},switchIcon:{width:34,height:34,borderRadius:11,backgroundColor:COLORS.primarySoft,alignItems:'center',justifyContent:'center',marginRight:10},switchTitle:{fontSize:11.5,fontWeight:'900',color:COLORS.text},switchSub:{fontSize:9.2,color:COLORS.muted,marginTop:2,lineHeight:14}});
