import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { OwnerLayout } from '../../components/common/OwnerLayout';
import { ActionButton } from '../../components/common/ActionButton';
import { Card, SectionTitle } from '../../components/common/OwnerUI';
import { COLORS, RADIUS } from '../../constants/theme';
import { reservationStats } from '../../utils/mockData';

export default function Analytics() { const router = useRouter(); return <OwnerLayout active="more" title="Analytics"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><View style={styles.hero}><Text style={styles.kicker}>PERFORMANCE</Text><Text style={styles.title}>Today's analytics</Text><Text style={styles.sub}>A quick view of demand, guest flow and table performance.</Text></View><Card style={styles.highlight}><View style={styles.highlightIcon}><Ionicons name="trending-up" size={20} color={COLORS.text}/></View><View style={{flex:1}}><Text style={styles.highlightTitle}>Restaurant activity is healthy</Text><Text style={styles.highlightSub}>Reservations and table usage are on track today.</Text></View><Text style={styles.growth}>+12%</Text></Card><SectionTitle title="Key metrics"/><View style={styles.grid}>{[['8','Reservations','calendar-outline',COLORS.red],['6','Queue guests','people-outline',COLORS.purple],['9','Occupied tables','grid-outline',COLORS.orange],['75%','Table utilization','analytics-outline',COLORS.green]].map(([v,l,i,c])=><View key={l} style={styles.metric}><View style={[styles.metricIcon,{backgroundColor:(c as string)+'18'}]}><Ionicons name={i as any} size={17} color={c as string}/></View><Text style={styles.metricValue}>{v}</Text><Text style={styles.metricLabel}>{l}</Text></View>)}</View><Card><Text style={styles.sectionHeading}>Guest flow</Text><View style={styles.flowRow}><Flow label="Reservations" value={8} max={10} tint={COLORS.red}/><Flow label="Walk-ins" value={5} max={10} tint={COLORS.orange}/><Flow label="Queue" value={6} max={10} tint={COLORS.purple}/></View></Card><ActionButton title="Generate detailed report" onPress={() => router.push('/(owner)/reports')} icon={<Ionicons name="document-text-outline" size={17} color={COLORS.text}/>} style={{marginTop:12}}/></ScrollView></OwnerLayout>; }
function Flow({label,value,max,tint}:{label:string;value:number;max:number;tint:string}){return <View style={styles.flow}><View style={styles.flowTop}><Text style={styles.flowLabel}>{label}</Text><Text style={styles.flowValue}>{value}</Text></View><View style={styles.track}><View style={[styles.fill,{width:`${Math.min(100,value/max*100)}%`,backgroundColor:tint}]}/></View></View>}
const styles=StyleSheet.create({scroll:{paddingTop:5,paddingBottom:24},hero:{marginBottom:14},kicker:{fontSize:8.5,fontWeight:'900',color:COLORS.muted,letterSpacing:1.1,marginBottom:3},title:{fontSize:24,fontWeight:'900',color:COLORS.text},sub:{fontSize:10.5,lineHeight:15,color:COLORS.textSoft,marginTop:3},highlight:{flexDirection:'row',alignItems:'center',padding:13,backgroundColor:COLORS.primarySoft,borderColor:'#F1E4AA'},highlightIcon:{width:38,height:38,borderRadius:13,backgroundColor:COLORS.primary,alignItems:'center',justifyContent:'center',marginRight:10},highlightTitle:{fontSize:11.5,fontWeight:'900',color:COLORS.text},highlightSub:{fontSize:9.2,color:'#7B7354',marginTop:3},growth:{fontSize:14,fontWeight:'900',color:COLORS.green},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'},metric:{width:'48.2%',minHeight:82,backgroundColor:COLORS.surface,borderRadius:RADIUS.md,borderWidth:1,borderColor:'#ECECE8',padding:11,marginBottom:9},metricIcon:{width:30,height:30,borderRadius:10,alignItems:'center',justifyContent:'center',marginBottom:6},metricValue:{fontSize:20,fontWeight:'900',color:COLORS.text},metricLabel:{fontSize:9.5,color:COLORS.muted,marginTop:2},sectionHeading:{fontSize:13,fontWeight:'900',marginBottom:10,color:COLORS.text}, flowRow: {flexDirection: 'row',justifyContent: 'space-between',gap: 12,},flow: {flex: 1,marginBottom: 11,},flowTop:{flexDirection:'row',justifyContent:'space-between',marginBottom:5},flowLabel:{fontSize:10,color:COLORS.textSoft},flowValue:{fontSize:10,fontWeight:'900'},track:{height:7,borderRadius:4,backgroundColor:'#EEEEEA',overflow:'hidden'},fill:{height:7,borderRadius:4}});
