import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { OwnerLayout } from '../../components/common/OwnerLayout';
import { ActionButton } from '../../components/common/ActionButton';
import { Card, StatusPill } from '../../components/common/OwnerUI';
import { COLORS } from '../../constants/theme';

const initial = [
  { id: 'Q1', position: 1, name: 'Priya Silva', guests: 2, wait: 5, phone: '071 987 6543' }, { id: 'Q2', position: 2, name: 'Nuwan Perera', guests: 4, wait: 12, phone: '077 345 2211' }, { id: 'Q3', position: 3, name: 'Hansika Silva', guests: 3, wait: 18, phone: '076 111 9034' },
];
export default function OwnerQueue() { const router = useRouter(); const [tab, setTab] = useState<'Waiting'|'Seated'>('Waiting'); const [items, setItems] = useState(initial);
  const notify = (id: string) => { Alert.alert('Customer notified', 'The guest has been notified that their table is ready.'); setItems(prev => prev.filter(item => item.id !== id)); };
  return <OwnerLayout active="queue" title="Virtual Queue"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><View style={styles.top}><View style={{ flex:1 }}><Text style={styles.kicker}>LIVE QUEUE</Text><Text style={styles.title}>Virtual Queue</Text><Text style={styles.sub}>Keep guests moving with clear wait times and fast seating.</Text></View><Pressable onPress={() => router.push('/(owner)/staff')} style={styles.add}><Ionicons name="add" size={18} color={COLORS.text}/><Text style={styles.addText}>Walk-in</Text></Pressable></View><View style={styles.tabs}>{(['Waiting','Seated'] as const).map(item => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.tabActive]}><Text style={[styles.tabText, tab === item && styles.tabTextActive]}>{item} ({item === 'Waiting' ? items.length : 2})</Text></Pressable>)}</View>{tab === 'Waiting' ? items.map(item => <Card key={item.id} style={styles.queueCard}><View style={styles.position}><Text style={styles.positionText}>#{item.position}</Text></View><View style={styles.main}><View style={styles.nameRow}><Text style={styles.name}>{item.name}</Text><StatusPill label={`~ ${item.wait} min`} tone="yellow" /></View><Text style={styles.meta}>{item.guests} Guests · {item.phone}</Text><View style={styles.actions}><Pressable onPress={() => notify(item.id)} style={styles.action}><Ionicons name="notifications-outline" size={15} color={COLORS.text}/><Text style={styles.actionText}>Notify</Text></Pressable><Pressable onPress={() => Alert.alert('Seat guest', `Choose an available table for ${item.name}.`)} style={[styles.action, styles.actionDark]}><Ionicons name="restaurant-outline" size={15} color={COLORS.white}/><Text style={[styles.actionText, { color: COLORS.white }]}>Seat</Text></Pressable></View></View></Card>) : <View style={styles.seated}><Ionicons name="checkmark-done-circle-outline" size={36} color={COLORS.green}/><Text style={styles.seatedTitle}>Two parties are seated</Text><Text style={styles.seatedSub}>Seated guests will move out of the active waiting queue.</Text></View>}<ActionButton title="Add walk-in customer" onPress={() => router.push('/(owner)/staff')} variant="outline" style={{ marginTop: 4 }} /></ScrollView></OwnerLayout>; }
const styles = StyleSheet.create({ scroll:{paddingTop:5,paddingBottom:24},top:{flexDirection:'row',alignItems:'center',marginBottom:14},kicker:{fontSize:8.5,fontWeight:'900',color:COLORS.muted,letterSpacing:1.1,marginBottom:3},title:{fontSize:24,fontWeight:'900',color:COLORS.text},sub:{fontSize:10.5,lineHeight:15,color:COLORS.textSoft,marginTop:3},add:{minHeight:40,paddingHorizontal:11,borderRadius:20,backgroundColor:COLORS.primary,flexDirection:'row',alignItems:'center',gap:4},addText:{fontSize:9.5,fontWeight:'900'},tabs:{flexDirection:'row',backgroundColor:'#E8E8E4',padding:3,borderRadius:18,marginBottom:11},tab:{flex:1,minHeight:36,borderRadius:15,alignItems:'center',justifyContent:'center'},tabActive:{backgroundColor:COLORS.primary},tabText:{fontSize:10,fontWeight:'700',color:COLORS.textSoft},tabTextActive:{color:COLORS.text,fontWeight:'900'},queueCard:{flexDirection:'row',padding:10},position:{width:42,height:42,borderRadius:14,backgroundColor:COLORS.primarySoft,alignItems:'center',justifyContent:'center'},positionText:{fontSize:13,fontWeight:'900'},main:{flex:1,marginLeft:10},nameRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},name:{fontSize:12.5,fontWeight:'900',color:COLORS.text},meta:{fontSize:9.5,color:COLORS.muted,marginTop:4},actions:{flexDirection:'row',gap:7,marginTop:8},action:{minHeight:32,borderRadius:10,paddingHorizontal:11,backgroundColor:'#F4F4F1',flexDirection:'row',alignItems:'center',gap:5},actionDark:{backgroundColor:COLORS.black},actionText:{fontSize:9.5,fontWeight:'800'},seated:{backgroundColor:COLORS.surface,borderRadius:18,borderWidth:1,borderColor:'#ECECE8',padding:30,alignItems:'center',marginBottom:10},seatedTitle:{fontSize:14,fontWeight:'900',marginTop:9,color:COLORS.text},seatedSub:{fontSize:10,color:COLORS.muted,textAlign:'center',lineHeight:15,marginTop:4}});
