import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { OwnerLayout } from '../../components/common/OwnerLayout';
import { SearchBar, StatusPill } from '../../components/common/OwnerUI';
import { COLORS } from '../../constants/theme';

const reservations = [
  { id: 'R1', time: '12:00 PM', name: 'Thilina Fernando', guests: 3, table: 'Table 3', status: 'Arriving', day: 'Today' }, { id: 'R2', time: '1:30 PM', name: 'Samantha Dias', guests: 2, table: 'Table 5', status: 'Confirmed', day: 'Today' }, { id: 'R3', time: '7:00 PM', name: 'Chen Family', guests: 5, table: 'Table 8', status: 'Confirmed', day: 'Today' }, { id: 'R4', time: '7:30 PM', name: 'Nisal Perera', guests: 4, table: 'Table 1', status: 'Confirmed', day: 'Today' }, { id: 'R5', time: '12:00 PM', name: 'Thilina Fernando', guests: 3, table: 'Table 3', status: 'Arriving', day: 'Tomorrow' }, { id: 'R6', time: '1:30 PM', name: 'Samantha Dias', guests: 2, table: 'Table 5', status: 'Confirmed', day: 'Tomorrow' },
];

export default function OwnerReservations() {
  const router = useRouter(); const [search, setSearch] = useState(''); const [tab, setTab] = useState('Upcoming');
  const filtered = useMemo(() => reservations.filter(r => `${r.name} ${r.table} ${r.time}`.toLowerCase().includes(search.toLowerCase()) && (tab === 'Upcoming' || tab === r.status)), [search, tab]);
  return <OwnerLayout active="reservations" title="Reservation"><FlatList data={filtered} keyExtractor={r => r.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.list} ListHeaderComponent={<View><View style={styles.intro}><Text style={styles.title}>Reservation</Text><Text style={styles.count}>{filtered.length} upcoming</Text></View><SearchBar value={search} onChangeText={setSearch} placeholder="Search name, phone or booking ID" /><View style={styles.tabs}>{['Upcoming','Arriving','Confirmed'].map(item => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.tabActive]}><Text style={[styles.tabText, tab === item && styles.tabTextActive]}>{item}</Text></Pressable>)}</View></View>} renderItem={({ item, index }) => <Pressable onPress={() => router.push('/(owner)/reservations')} style={({ pressed }) => [styles.card, pressed && { transform: [{ scale: 0.99 }] }]}><View style={styles.time}><Text style={styles.timeMain}>{item.time}</Text><Text style={styles.day}>{index < 4 ? 'Today' : 'Tomorrow'}</Text></View><View style={styles.main}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.guests} Guests · {item.table}</Text><StatusPill label={item.status} tone={item.status === 'Arriving' ? 'blue' : 'green'} /></View><Ionicons name="chevron-forward" size={18} color="#90908B" /></Pressable>} ListEmptyComponent={<View style={styles.empty}><Ionicons name="calendar-clear-outline" size={27} color={COLORS.muted} /><Text style={styles.emptyTitle}>No reservations found</Text><Text style={styles.emptySub}>Try a different search or status filter.</Text></View>} /></OwnerLayout>;
}

const styles = StyleSheet.create({ list: { paddingTop: 5, paddingBottom: 24 }, intro: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }, title: { fontSize: 24, fontWeight: '900', color: COLORS.text }, count: { fontSize: 9.5, color: COLORS.muted }, tabs: { flexDirection: 'row', gap: 7, marginBottom: 12 }, tab: { flex: 1, minHeight: 36, borderRadius: 18, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: '#E3E3DF', alignItems: 'center', justifyContent: 'center' }, tabActive: { backgroundColor: COLORS.black, borderColor: COLORS.black }, tabText: { fontSize: 9.5, fontWeight: '700', color: COLORS.textSoft }, tabTextActive: { color: COLORS.white, fontWeight: '800' }, card: { minHeight: 73, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: '#ECECE8', borderRadius: 16, padding: 10, flexDirection: 'row', alignItems: 'center', marginBottom: 8 }, time: { width: 62, alignItems: 'center', paddingRight: 6, borderRightWidth: 1, borderRightColor: '#EEEEEA' }, timeMain: { fontSize: 11, fontWeight: '900', color: COLORS.text }, day: { fontSize: 8, color: COLORS.muted, marginTop: 3 }, main: { flex: 1, paddingHorizontal: 10 }, name: { fontSize: 11.5, fontWeight: '900', color: COLORS.text }, meta: { fontSize: 9.2, color: COLORS.muted, marginTop: 2, marginBottom: 5 }, empty: { backgroundColor: COLORS.surface, borderRadius: 18, padding: 28, alignItems: 'center', marginTop: 8 }, emptyTitle: { fontSize: 14, fontWeight: '900', marginTop: 8, color: COLORS.text }, emptySub: { fontSize: 10, color: COLORS.muted, marginTop: 3 } });
