import { useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Field, Heading, Label, Screen, State, money, type Notification, type Order } from '@dineflow/shared';
import { api } from '../lib/api';
import { useAuth } from '../stores/auth.store';
import { useRealtime } from './data';
export function Profile(){const router=useRouter();const {profile,refresh,signOut}=useAuth();const [name,setName]=useState(profile?.full_name??'');const [phone,setPhone]=useState(profile?.phone??'');const [busy,setBusy]=useState(false);const client=useQueryClient();const orders=useQuery({queryKey:['orders'],queryFn:()=>api<Order[]>('/orders')});return <Screen title="Your account" subtitle="Manage your details and alerts."><Field label="Full name" value={name} onChangeText={setName}/><Field label="Phone" keyboardType="phone-pad" value={phone} onChangeText={setPhone}/><Button title="Save profile" busy={busy} onPress={async()=>{setBusy(true);try{await api('/me',{method:'PATCH',body:{full_name:name,phone}});await refresh();Alert.alert('Saved','Your profile was updated.');}catch(e){Alert.alert('Could not save',String((e as Error).message));}finally{setBusy(false);}}}/><Button title="Notifications" kind="secondary" onPress={()=>router.push('/notifications')}/><Heading>Pre-orders</Heading>{orders.isLoading?<State loading/>:orders.data?.length?orders.data.map(o=><Card key={o.id}><Label>{new Date(o.created_at).toLocaleString()}</Label><Label>{o.status} · {money(o.total_cents)} · {o.order_items.length} items</Label>{o.status==='PLACED'&&<Button title="Cancel pre-order" kind="danger" onPress={()=>Alert.alert('Cancel pre-order?',undefined,[{text:'Back'},{text:'Cancel',style:'destructive',onPress:async()=>{await api(`/orders/${o.id}`,{method:'PATCH',body:{status:'CANCELLED'}});await client.invalidateQueries({queryKey:['orders']})}}])}/>}</Card>):<State empty="No pre-orders yet."/>}<Button title="Sign out" kind="ghost" onPress={async()=>{await signOut();router.replace('/login')}}/></Screen>}
export function Notifications(){const profile=useAuth(s=>s.profile);useRealtime('notifications',profile?`user_id=eq.${profile.id}`:undefined);const client=useQueryClient();const q=useQuery({queryKey:['notifications'],queryFn:()=>api<Notification[]>('/notifications')});return <Screen title="Notifications" subtitle="Reservation reminders and table-ready updates.">{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:q.data?.length?q.data.map(n=><Card key={n.id}><Heading>{n.title}</Heading><Label>{n.body}</Label><Label muted>{new Date(n.created_at).toLocaleString()}</Label>{!n.read_at&&<Button title="Mark read" kind="secondary" onPress={async()=>{await api(`/notifications/${n.id}`,{method:'PATCH'});await client.invalidateQueries({queryKey:['notifications']})}}/>}</Card>):<State empty="No notifications yet."/>}</Screen>}
