import { useState } from 'react';
import { Alert, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Field, Freshness, Heading, Label, Screen, State, StatusBadge, type Restaurant, type Reservation, type Table } from '@dineflow/shared';
import { api } from '../lib/api';
import { useBooking } from '../stores/booking.store';
import { useRealtime } from './data';
const currentDate=()=>new Date(Date.now()+330*60000).toISOString().slice(0,10);
const validDate=(value:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const parsed=new Date(`${value}T00:00:00+05:30`);return !Number.isNaN(parsed.getTime())&&new Date(parsed.getTime()+330*60000).toISOString().slice(0,10)===value};
const validTime=(value:string)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(value);
const startIso=(date:string,time:string)=>new Date(`${date}T${time}:00+05:30`).toISOString();
const format=(s:string)=>new Date(s).toLocaleString();
export function Home(){const router=useRouter();const booking=useBooking();const restaurants=useQuery({queryKey:['restaurants'],queryFn:()=>api<Restaurant[]>('/restaurants')});return <Screen title="Find your table" subtitle="Choose a restaurant and see when a table is available.">{restaurants.isLoading?<State loading/>:restaurants.error?<State error={restaurants.error.message} onRetry={()=>void restaurants.refetch()}/>:restaurants.data?.map(r=><Card key={r.id}><Heading>{r.name}</Heading><Label muted>{r.description||r.address||'Welcome to DineFlow'}</Label><Button title="Book a table" onPress={()=>{booking.reset();booking.set({restaurantId:r.id});router.push('/booking/select-date')}}/><Button title="Join queue" kind="secondary" onPress={()=>{booking.set({restaurantId:r.id});router.push('/queue/join')}}/><Button title="View menu" kind="ghost" onPress={()=>{booking.set({restaurantId:r.id});router.push('/menu')}}/></Card>)}</Screen>}
export function SelectDate(){const b=useBooking();const router=useRouter();return <Screen title="Choose a date" subtitle="When would you like to visit?"><Field label="Date (YYYY-MM-DD)" value={b.date} placeholder={currentDate()} keyboardType="numbers-and-punctuation" onChangeText={date=>b.set({date})}/><Button title="Continue" disabled={!validDate(b.date)||b.date<currentDate()} onPress={()=>router.push('/booking/select-time')}/></Screen>}
export function SelectTime(){const b=useBooking();const router=useRouter();return <Screen title="Choose a time" subtitle="Lunch and dinner slots are available according to restaurant opening hours."><Field label="Time (24-hour HH:MM)" value={b.time} keyboardType="numbers-and-punctuation" onChangeText={time=>b.set({time})}/><Button title="Continue" disabled={!validTime(b.time)} onPress={()=>router.push('/booking/select-guests')}/></Screen>}
export function SelectGuests(){const b=useBooking();const router=useRouter();return <Screen title="Party size" subtitle="How many guests are coming?"><Field label="Guests" value={String(b.partySize)} keyboardType="number-pad" onChangeText={s=>b.set({partySize:Number(s)||0})}/><Button title="Find tables" disabled={b.partySize<1||b.partySize>20} onPress={()=>router.push('/booking/select-table')}/></Screen>}
export function SelectTable(){const b=useBooking();const router=useRouter();useRealtime('tables',b.restaurantId?`restaurant_id=eq.${b.restaurantId}`:undefined);useRealtime('reservations',b.restaurantId?`restaurant_id=eq.${b.restaurantId}`:undefined);
  const available=useQuery({queryKey:['availability',b.restaurantId,b.date,b.time,b.partySize,b.reservationId],enabled:!!b.restaurantId&&!!b.date&&!!b.time,queryFn:()=>api<{tables:Table[];updated_at:string}>(`/restaurants/${b.restaurantId}/availability?starts_at=${encodeURIComponent(startIso(b.date,b.time))}&party_size=${b.partySize}${b.reservationId?`&reservation_id=${b.reservationId}`:''}`)});
  return <Screen title="Available tables" subtitle={`${b.partySize} guests · ${b.date} at ${b.time}`}>{available.isLoading?<State loading/>:available.error?<State error={available.error.message} onRetry={()=>void available.refetch()}/>:<><Freshness at={available.data?.updated_at}/>{available.data?.tables.length?<>{available.data.tables.map(t=><Card key={t.id}><Heading>{t.label}</Heading><Label muted>Seats up to {t.capacity}</Label><Button title="Select table" kind={b.tableId===t.id?'primary':'secondary'} onPress={()=>{b.set({tableId:t.id});router.push('/booking/special-request')}}/></Card>)}</>:<Card><Heading>No tables available</Heading><Label muted>Try another time or join the virtual queue.</Label><Button title="Join queue" onPress={()=>router.push('/queue/join')}/></Card>}</>}</Screen>}
export function SpecialRequest(){const b=useBooking();const router=useRouter();const [busy,setBusy]=useState(false);const client=useQueryClient();return <Screen title="Review your booking" subtitle="Confirm your details before reserving."><Card><Label>{b.date} at {b.time}</Label><Label>{b.partySize} guests</Label><Label muted>Selected table: {b.tableId?'Yes':'Automatic'}</Label></Card><Field label="Special requests (optional)" multiline value={b.specialRequest} onChangeText={specialRequest=>b.set({specialRequest})}/><Button title={b.reservationId?'Save changes':'Confirm reservation'} busy={busy} onPress={async()=>{setBusy(true);try{await api(b.reservationId?`/reservations/${b.reservationId}`:'/reservations',{method:b.reservationId?'PATCH':'POST',body:{...(b.reservationId?{}:{restaurant_id:b.restaurantId}),starts_at:startIso(b.date,b.time),party_size:b.partySize,table_id:b.tableId??undefined,special_request:b.specialRequest}});await client.invalidateQueries();router.replace('/booking/confirmation');}catch(e){Alert.alert('Could not book',String((e as Error).message));}finally{setBusy(false);}}}/></Screen>}
export function Confirmation(){const router=useRouter();const reset=useBooking(s=>s.reset);return <Screen title="Table reserved" subtitle="Your booking is confirmed. You can review or cancel it from Bookings."><Card><StatusBadge status="CONFIRMED"/><Label>Your restaurant will be ready for you at the selected time.</Label></Card><Button title="View bookings" onPress={()=>{reset();router.replace('/reservations')}}/><Button title="Browse menu" kind="secondary" onPress={()=>router.push('/menu')}/></Screen>}
export function Reservations(){const client=useQueryClient();const router=useRouter();const booking=useBooking();useRealtime('reservations');const query=useQuery({queryKey:['reservations'],queryFn:()=>api<Reservation[]>('/reservations')});const cancel=useMutation({mutationFn:(id:string)=>api(`/reservations/${id}`,{method:'PATCH',body:{status:'CANCELLED'}}),onSuccess:()=>void client.invalidateQueries({queryKey:['reservations']})});
  return <Screen title="Your bookings" subtitle="Review upcoming and previous visits.">{query.isLoading?<State loading/>:query.error?<State error={query.error.message} onRetry={()=>void query.refetch()}/>:query.data?.length?query.data.map(r=><Card key={r.id}><Heading>{format(r.starts_at)}</Heading><StatusBadge status={r.status}/><Label>{r.party_size} guests</Label>{r.special_request&&<Label muted>{r.special_request}</Label>}{['PENDING','CONFIRMED'].includes(r.status)&&new Date(r.starts_at)>new Date()&&<><Button title="Change booking" kind="secondary" onPress={()=>{const local=new Date(r.starts_at).toLocaleString('sv-SE',{timeZone:'Asia/Colombo',hour12:false});booking.set({restaurantId:r.restaurant_id,reservationId:r.id,date:local.slice(0,10),time:local.slice(11,16),partySize:r.party_size,tableId:r.table_id,specialRequest:r.special_request??''});router.push('/booking/select-date')}}/><Button title="Cancel booking" kind="danger" onPress={()=>Alert.alert('Cancel booking?','This will release your table.',[{text:'Keep booking'},{text:'Cancel booking',style:'destructive',onPress:()=>cancel.mutate(r.id)}])}/></>}</Card>):<State empty="No bookings yet."/>}<Button title="Book a table" onPress={()=>{booking.reset();router.push('/home')}}/></Screen>}
