import { useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Heading, Label, Screen, State, money, type Product, type Restaurant, type Reservation } from '@dineflow/shared';
import { api } from '../lib/api';
import { useBooking } from '../stores/booking.store';
import { useCart } from '../stores/cart.store';
export function Menu(){const router=useRouter();const b=useBooking();const restaurants=useQuery({queryKey:['restaurants'],queryFn:()=>api<Restaurant[]>('/restaurants')});const id=b.restaurantId??restaurants.data?.[0]?.id;const q=useQuery({queryKey:['products',id],enabled:!!id,queryFn:()=>api<Product[]>(`/products?restaurant_id=${id}`)});const add=useCart(s=>s.add);return <Screen title="Menu" subtitle="Explore dishes and add your favorites to your cart.">{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:q.data?.length?q.data.map(p=><Card key={p.id}><Heading>{p.name}</Heading><Label muted>{p.description}</Label><Label>{money(p.price_cents)}</Label><Button title="View details" kind="secondary" onPress={()=>{b.set({restaurantId:p.restaurant_id});router.push(`/menu/${p.id}`)}}/><Button title="Add to cart" onPress={()=>{b.set({restaurantId:p.restaurant_id});add(p)}}/></Card>):<State empty="No menu items available."/>}<Button title="View cart" kind="secondary" onPress={()=>router.push('/cart')}/></Screen>}
export function ProductDetail(){const router=useRouter();const {productId}=useLocalSearchParams<{productId:string}>();const b=useBooking();const q=useQuery({queryKey:['products',b.restaurantId],enabled:!!b.restaurantId,queryFn:()=>api<Product[]>(`/products?restaurant_id=${b.restaurantId}`)});const p=q.data?.find(x=>x.id===productId);const add=useCart(s=>s.add);return <Screen title={p?.name??'Menu item'}>{q.isLoading?<State loading/>:p?<Card><Label muted>{p.description}</Label><Heading>{money(p.price_cents)}</Heading><Button title="Add to cart" onPress={()=>{add(p);router.push('/cart')}}/></Card>:<State empty="Product not found."/>}</Screen>}
export function Cart(){const router=useRouter();const items=useCart(s=>s.items);const remove=useCart(s=>s.remove);return <Screen title="Your cart" subtitle="Review your pre-order before placing it.">{items.length?items.map(i=><Card key={i.product.id}><Heading>{i.product.name}</Heading><Label>{i.quantity} × {money(i.product.price_cents)}</Label><Button title="Remove" kind="danger" onPress={()=>remove(i.product.id)}/></Card>):<State empty="Your cart is empty."/>}<Heading>Total: {money(items.reduce((n,i)=>n+i.product.price_cents*i.quantity,0))}</Heading><Button title="Continue" disabled={!items.length} onPress={()=>router.push('/cart/checkout')}/></Screen>}
export function Checkout(){const router=useRouter();const items=useCart(s=>s.items);const clear=useCart(s=>s.clear);const b=useBooking();const [busy,setBusy]=useState(false);const [requestId]=useState(()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`);const client=useQueryClient();const reservations=useQuery({queryKey:['reservations'],queryFn:()=>api<Reservation[]>('/reservations')});const active=reservations.data?.find(r=>r.restaurant_id===b.restaurantId&&['PENDING','CONFIRMED','ARRIVED'].includes(r.status));return <Screen title="Place pre-order" subtitle="Your items will be linked to your reservation when one is available."><Card><Label>{items.length} menu items</Label><Heading>{money(items.reduce((n,i)=>n+i.product.price_cents*i.quantity,0))}</Heading>{active&&<Label muted>Linked to booking {new Date(active.starts_at).toLocaleString()}</Label>}</Card><Button title="Place order" busy={busy} disabled={!items.length} onPress={async()=>{setBusy(true);try{await api('/orders',{method:'POST',body:{restaurant_id:b.restaurantId??items[0].product.restaurant_id,reservation_id:active?.id,request_id:requestId,items:items.map(i=>({product_id:i.product.id,quantity:i.quantity}))}});await client.invalidateQueries({queryKey:['orders']});clear();Alert.alert('Order placed','Your pre-order has been recorded.');router.replace('/menu');}catch(e){Alert.alert('Could not place order',String((e as Error).message));}finally{setBusy(false);}}}/></Screen>}
