import { useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Field, Freshness, Heading, Label, Screen, State, StatusBadge, type QueueEntry } from '@dineflow/shared';
import { api } from '../lib/api';
import { useBooking } from '../stores/booking.store';
import { useAuth } from '../stores/auth.store';
import { useRealtime } from './data';
export function Queue(){const router=useRouter();const me=useAuth(s=>s.profile);useRealtime('queue_entries',me?`customer_id=eq.${me.id}`:undefined);const q=useQuery({queryKey:['queue'],queryFn:()=>api<QueueEntry[]>('/queue'),refetchInterval:30000});const active=q.data?.find(e=>['WAITING','NOTIFIED','TABLE_READY'].includes(e.status));return <Screen title="Virtual queue" subtitle="Track your place without waiting in line.">{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:active?<Card><StatusBadge status={active.status}/><Heading>{active.status==='TABLE_READY'?'Your table is ready!':`Position ${active.position??'—'}`}</Heading><Label>Estimated wait: {active.estimated_wait_minutes} minutes</Label><Freshness at={active.updated_at}/><Button title={active.status==='TABLE_READY'?'View table-ready details':'View queue progress'} onPress={()=>router.push('/queue/status')}/></Card>:<State empty="You are not in a queue."/>}<Button title="Join a queue" onPress={()=>router.push('/queue/join')}/></Screen>}
export function JoinQueue(){const router=useRouter();const b=useBooking();const profile=useAuth(s=>s.profile);const [name,setName]=useState(profile?.full_name??'');const [phone,setPhone]=useState(profile?.phone??'');const [party,setParty]=useState(String(b.partySize));const [busy,setBusy]=useState(false);const client=useQueryClient();return <Screen title="Join the queue" subtitle="We will keep your place and let you know when a table is ready."><Field label="Name" value={name} onChangeText={setName}/><Field label="Phone (optional)" value={phone} keyboardType="phone-pad" onChangeText={setPhone}/><Field label="Guests" value={party} keyboardType="number-pad" onChangeText={setParty}/><Button title="Join queue" busy={busy} disabled={!b.restaurantId||!name||!Number(party)} onPress={async()=>{setBusy(true);try{await api('/queue',{method:'POST',body:{restaurant_id:b.restaurantId,customer_name:name,phone,party_size:Number(party)}});await client.invalidateQueries({queryKey:['queue']});router.replace('/queue/status');}catch(e){Alert.alert('Could not join queue',String((e as Error).message));}finally{setBusy(false);}}}/></Screen>}
export function QueueStatus(){const router=useRouter();const me=useAuth(s=>s.profile);useRealtime('queue_entries',me?`customer_id=eq.${me.id}`:undefined);useRealtime('notifications',me?`user_id=eq.${me.id}`:undefined);const client=useQueryClient();const q=useQuery({queryKey:['queue'],queryFn:()=>api<QueueEntry[]>('/queue'),refetchInterval:30000});const active=q.data?.find(e=>['WAITING','NOTIFIED','TABLE_READY'].includes(e.status));return <Screen title={active?.status==='TABLE_READY'?'Your table is ready!':'Queue progress'} subtitle={active?.status==='TABLE_READY'?'Please return to the restaurant and check in with staff.':'We will update your position as tables become available.'}>{q.isLoading?<State loading/>:q.error?<State error={q.error.message} onRetry={()=>void q.refetch()}/>:active?<Card><StatusBadge status={active.status}/><Heading>{active.status==='TABLE_READY'?'Head to the restaurant':`#${active.position??'—'} in line`}</Heading><Label>Estimated wait: {active.estimated_wait_minutes} minutes</Label><Freshness at={active.updated_at}/><Button title="Cancel queue entry" kind="danger" onPress={()=>Alert.alert('Leave queue?','You will lose your position.',[{text:'Stay'},{text:'Leave',style:'destructive',onPress:async()=>{try{await api(`/queue/${active.id}`,{method:'PATCH',body:{status:'CANCELLED'}});await client.invalidateQueries({queryKey:['queue']});router.replace('/queue');}catch(e){Alert.alert('Could not leave queue',String((e as Error).message));}}}])}/></Card>:<State empty="No active queue entry."/>}<Button title="Notifications" kind="secondary" onPress={()=>router.push('/notifications')}/></Screen>}
export function TableReady(){return <QueueStatus/>}
